### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by Luterngun** [learnleft/learnleft.github.io#1]
[https://github.com/learnleft/learnleft.github.io/blob/main/%E5%A5%96%E5%8A%B1%E8%B5%84%E6%BA%90/1.md](https://github.com/learnleft/learnleft.github.io/blob/main/%E5%A5%96%E5%8A%B1%E8%B5%84%E6%BA%90/1.md)

1. 编程随想的博客链接末尾加了“/”之后无法直接打开（显示“抱歉，您在此博客中要查找的页面不存在。”），去掉后才行，劳烦您看看能否复现这个问题。

2. 2047改版成了类似 Reddit 的分组论坛模式，2047 小组的技术专栏链接是 https://2047.one/g/2047/c/4 （另外“国家局域网研究所”是“讨论互联网审查和其他科技消息”的小组，链接是 https://2047.one/g/%E5%9B%BD%E5%AE%B6%E5%B1%80%E5%9F%9F%E7%BD%91%E7%A0%94%E7%A9%B6%E6%89%80 ）

**Comment by learnleft** [comment]
改好了
